FROM alpine/helm:VERSION
ENV HOME /tmp

#FIXME: add versioning to helm-s3

RUN helm init -c --stable-repo-url https://charts.helm.sh/stable/ && \
    apk add --update --no-cache git bash && \
    helm plugin install https://github.com/hypnoglow/helm-s3.git && \
    rm -f /var/cache/apk/* && \
    ln -s /usr/bin/helm /usr/bin/helmnoaws

# Fake a repo when entrypoint is overridden
ADD repositories.yaml $HELM_HOME/repository/repositories.yaml
ADD cache.yaml $HELM_HOME/repository/cache/infobloxcto-index.yaml

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh", "helm"]
CMD ["--help"]
