name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'test-tags'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name:
          make docker-build
          make test
      - name: Build and push
        run: |
          make docker-push
